### ISSUE TITLE
Missing license?

### ISSUE THREAD

**Issue by Nolski** [DevProgress/ortiz#4]
First, the standard disclaimer: I am not a lawyer, and this does not constitute legal or financial advice.

Generally, IMHO, it is a good idea to use FSF or OSI Approved Licenses (which can be found here https://www.gnu.org/licenses/licenses.html and here https://opensource.org/licenses/category)

The Free Software Foundation has a useful guide for choosing a license: https://www.gnu.org/licenses/license-recommendations.html

I often reference the Software Freedom Law Center's Legal Primer for both practical and academic purposes (highly recommended): https://www.softwarefreedom.org/resources/2008/foss-primer.html#x1-60002.2

https://tldrlegal.com/ is quite a useful resource for comparing the various FOSS licenses out there once you have some context

To get ahold of actual lawyers/advisors who help FOSS projects, you can reach out to the FSF, SFLC, and OSI at:
licensing@fsf.org
help@softwarefreedom.org
license-discuss@opensource.org

Hope this helps, and happy hacking!

**Comment by jillh510** [comment]
According to @bradyk : "holzer, ortiz are campaign things so that’ll have to come from the campaign. we have to make sure to license just the code, and not the artwork"

**Comment by Nolski** [comment]
A good way to do this would be instead of adding a LICENSE file, you could put the license at the top of each file of code. Another option would be to leave a note in the README saying the artwork is licensed under something else.

**Comment by dxa4481** [comment]
This code is already licensed and exists in its entirety under this project https://github.com/DevProgress/maps-showcase

This repository you've found and commented on, is a relic of the deploy process @decause hacked together so that the code could ship to hillaryclinton.com without having relics like https://www.hillaryclinton.com/artist/ortiz/LICENSE and https://www.hillaryclinton.com/artist/ortiz/README.md

That's the way I understand it. You'll notice @decause also blew away the history on this repo, again, I believe the sole purpose of this was to hackily ship static files to the campaign that only contained the files intended to go into production
